<?php

/**
 * @file
 * This is an example outlining how a module can make use of the new DBTNG
 * database API.
 *
 * @todo Demonstrate transaction usage.
 *
 * General documentation is available at
 * @link database Database abstraction layer documentation @endlink and
 * at @link http://drupal.org/node/310069 @endlink.
 */

use Symfony\Component\HttpFoundation\Request;

/**
 * @defgroup dbtng_example Example: Database (DBTNG)
 * @ingroup examples
 * @{
 * Database examples, including DBTNG.
 *
 * 'DBTNG' means 'Database: The Next Generation.' Yes, Drupallers are nerds.
 *
 * General documentation is available at
 * @link database.inc database abstraction layer documentation @endlink and
 * at @link http://drupal.org/node/310069 Database API @endlink.
 *
 * The several examples in DBTNGExampleController (see
 * /lib/Drupal/dbtng_example/DBTNGExampleController.php) demonstrate
 * basic database usage.
 *
 * db_insert() example:
 * @code
 *   // INSERT INTO {dbtng_example} (name, surname) VALUES('John, 'Doe')
 *   db_insert('dbtng_example')
 *     ->fields(array('name' => 'John', 'surname' => 'Doe'))
 *     ->execute();
 * @endcode
 *
 * db_update() example:
 * @code
 *   // UPDATE {dbtng_example} SET name = 'Jane' WHERE name = 'John'
 *   db_update('dbtng_example')
 *     ->fields(array('name' => 'Jane'))
 *     ->condition('name', 'John')
 *     ->execute();
 * @endcode
 *
 * db_delete() example:
 * @code
 *   // DELETE FROM {dbtng_example} WHERE name = 'Jane'
 *   db_delete('dbtng_example')
 *     ->condition('name', 'Jane')
 *     ->execute();
 * @endcode
 *
 * See @link database Database Abstraction Layer @endlink
 * @see db_insert()
 * @see db_update()
 * @see db_delete()
 * @see drupal_write_record()
 */

/**
 * Implements hook_help().
 *
 * Show some help on each form provided by this module.
 */
function dbtng_example_help($route_name, Request $request) {
  $output = '';
  switch ($route_name) {
    case 'dbtng':
      $output = t('Generate a list of all entries in the database. There is no filter in the query.');
      break;

    case 'dbtng_advanced':
      $output = t('A more complex list of entries in the database.') . ' ';
      $output .= t('Only the entries with name = "John" and age older than 18 years are shown, the username of the person who created the entry is also shown.');
      break;

    case 'dbtng_update':
      $output = t('Demonstrates a database update operation.');
      break;

    case 'dbtng_add':
      $output = t('Add an entry to the dbtng_example table.');
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
function dbtng_example_menu() {
  $items = array();

  $items['examples/dbtng'] = array(
    'title' => 'DBTNG Example',
    'route_name' => 'dbtng',
  );
  $items['examples/dbtng/list'] = array(
    'title' => 'List',
    'route_name' => 'dbtng_list',
  );
  $items['examples/dbtng/add'] = array(
    'title' => 'Add entry',
    'route_name' => 'dbtng_add',
  );
  $items['examples/dbtng/update'] = array(
    'title' => 'Update entry',
    'route_name' => 'dbtng_update',
  );
  $items['examples/dbtng/advanced'] = array(
    'title' => 'Advanced list',
    'route_name' => 'dbtng_advanced',
  );

  return $items;
}

/**
 * @} End of "defgroup dbtng_example".
 */
