<?php

/**
 * @file
 * Contains Drupal\content_entity_example\content_entity_example.module
 */

/**
 * @defgroup content_entity_example Example: Content Entity
 * @ingroup examples
 * @{
 * Implement a Content entity.
 *
 * This module demonstrates implementing a Content Entity.
 *
 * This is an example of a fieldable content entity used to hold structured
 * information without the overhead of using a content type. It is defined
 * programmatically and we will expose the main techniques to handle and expose
 * the contents.
 *
 * We define a content entity named 'Contact'. With it, we demonstrate the main
 * tasks for an entity:
 * - define
 * - save
 * - load
 * - view
 * - edit
 * - delete
 * - control access
 *
 * Where ever possible, we use the amazing tools built into D8 natively.
 * }
 */

/**
 * Implements hook_permission().
 */
function content_entity_example_permission() {
  return array(
    'delete contact entity' => array(
      'title' => t('Delete entity content.'),
    ),
    'add contact entity' => array(
      'title' => t('Add entity content'),
    ),
    'view contact entity' => array(
      'title' => t('View entity content'),
    ),
    'edit contact entity' => array(
      'title' => t('Edit entity content'),
    ),
    'administer contact entity' => array(
      'title' => t('Administer settings'),
    ),
  );
}
