<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

/**
 * @defgroup js_example Example: JavaScript
 * @ingroup examples
 * @{
 * Examples using Drupal 8's built-in JavaScript.
 */

/**
 * Implements hook_theme().
 */
function js_example_theme() {
  return array(
    'js_example_accordion' => array(
      'template' => 'accordion',
      'variables' => array('title' => NULL),
    ),
  );
}

/**
 * Implements hook_menu_link_defaults().
 */
function js_example_menu_link_defaults() {
  $links['js_example.info'] = array(
    'link_title' => 'JavaScript Example',
    'description' => 'Some information about the JavaScript example.',
    'route_name' => 'js_example.info',
  );
  $links['js_example.weights'] = array(
    'link_title' => 'JS weighting in action',
    'description' => 'Show list weighting through JavaScript.',
    'route_name' => 'js_example.weights',
    'parent' => 'js_example.info',
  );
  $links['js_example.accordion'] = array(
    'link_title' => 'jQuery UI accordion',
    'description' => 'jQuery UI accordion demo.',
    'route_name' => 'js_example.accordion',
    'parent' => 'js_example.info',
  );
  return $links;
}

/**
 * @} End of "defgroup js_example".
 */
