<?php
/**
 * @file
 * Module file for phpunit_example.
 */

/**
 * @defgroup phpunit_example Example: PHPUnit
 * @ingroup examples
 * @{
 * This example demonstrates PHPUnit for Drupal 8 unit testing.
 */

/**
 * Implements hook_help().
 *
 * @see hook_help()
 */
function phpunit_example_help($path, $arg) {
  switch ($path) {
    case 'examples/phpunit_example':
      // Help text for the simple page registered for this path.
      return t('This is the help text for PHPUnit example.');
  }
}

/**
 * @} End of "defgroup phpunit_example".
 */
